services:
  app:
    container_name: fumis_auctions_app
    build: .
    command: nodemon --watch /usr/src/app -e js app.js
    ports:
      - "8000:8000"
    links:
      - "mongo:mongosrv"
  mongo:
    container_name: fumis_mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'