services:
  app:
    container_name: app_auctions
    build: .
    command: nodemon --watch /usr/src/app -e js app.js
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
    links:
      - "mongo:mongosrv"
  mongo:
    container_name: mongo_auctions
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
    - '27017:27017'