services:
  app:
    container_name: fumis_auctions
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
    links:
      - "mongo:mongosrv"
  mongo:
    container_name: fumis_mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'